Build modules on a "make" but only if needed

diff --git a/lib/module-common.mk.in b/lib/module-common.mk.in
--- a/lib/module-common.mk.in
+++ b/lib/module-common.mk.in
@@ -8,7 +8,7 @@
 # libfromhere = ../../../..        # as many .. as components in herefromlib
 # SUBDIRS = <subdir1> <subdir2>    # as many as there are subdirs
 # HEADERS_SCM = foo\#.scm
-# MODULES_SCM = foo.scm foo.sld foo-test.scm
+# MODULES_SCM = foo.scm foo.sld test.scm
 # MAIN_MODULES = foo
 # OTHER_RCFILES = makefile
 # include $(libfromhere)/module-common.mk
@@ -115,8 +115,21 @@ modules-pre:
 	    else \
 	      modref="$(herefromlib)/$$main_mod"; \
 	    fi; \
-	    echo ">>>> building module $$modref for $$target"; \
-	    $(rootfromhere)/gsc/gsc -:~~bin=$(srcdirpfx)$(rootfromhere)/bin,~~lib=$(srcdirpfx)$(rootfromhere)/lib,~~include=$(srcdirpfx)$(rootfromhere)/include -f -e "(let ((x (##build-module \"$$main_mod\" (quote $$target) (quote ((module-ref $$modref)))))) (if (not x) (begin (println \"*** module failed to build\") (exit 1))))"; \
+	    need_to_build_module=no; \
+	    build_dir="$$main_mod@gambit409003@$$target"; \
+	    if test ! -d "$$build_dir" \
+	         -o "$(rootfromhere)/gsc/gsc" -nt "$$build_dir" \
+	         -o -f "$$main_mod.sld" -a "$$main_mod.sld" -nt "$$build_dir" \
+	         -o -f "$$main_mod.scm" -a "$$main_mod.scm" -nt "$$build_dir" \
+	         -o -f "$$main_mod#.scm" -a "$$main_mod#.scm" -nt "$$build_dir"; then \
+	      need_to_build_module=yes; \
+	    fi; \
+	    if test "$$need_to_build_module" = "yes"; then \
+	      echo ">>>> building module $$modref for $$target"; \
+	      $(rootfromhere)/gsc/gsc -:~~bin=$(srcdirpfx)$(rootfromhere)/bin,~~lib=$(srcdirpfx)$(rootfromhere)/lib,~~include=$(srcdirpfx)$(rootfromhere)/include -f -e "(let ((x (##build-module \"$$main_mod\" (quote $$target) (quote ((module-ref $$modref)))))) (if (not x) (begin (println \"*** module failed to build\") (exit 1))))"; \
+	    else \
+	      echo ">>>> no need to build module $$modref for $$target"; \
+	    fi; \
 	  done; \
 	done
 
