Improved makefiles for prebuilt installers so that tests which cannot be run are skipped (for example testing the G5 build on an intel Mac).

diff --git a/prebuilt/macosx/build-phase2.in b/prebuilt/macosx/build-phase2.in
--- a/prebuilt/macosx/build-phase2.in
+++ b/prebuilt/macosx/build-phase2.in
@@ -16,6 +16,7 @@ PACKAGE_SUBDIR="@PACKAGE_SUBDIR@"
 PKGM="/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker"
 
 VARIANT="$1"
+RUN_TESTS="$2"
 
 SOURCE_DIR="$INSTALL_PREFIX"
 INSTALL_DIR="$INSTALL_PREFIX"
@@ -48,18 +49,35 @@ install_gambc()
   cd "$rootfromhere"
   make mostlyclean
   make
-#  make check > check.out 2>&1
-#  cat check.out
-#  if ( fgrep -e "============ ALL TESTS SUCCESSFUL" check.out > /dev/null ) ; then
-    make install
-    (cd "$SOURCE_DIR/$PACKAGE_VERSION" && bin/gsc syntax-case)
-#  else
-#    echo "============ TESTS FAILED"
-#    cleanup
-#    exit 1
-#  fi
-#  rm -f check.out
-echo ============ ALL TESTS SUCCESSFUL
+
+  if [ "$RUN_TESTS" == "0" ] ; then
+    echo "************ TESTS SKIPPED ($VARIANT variant)"
+  else
+
+    TESTS_SUCCESS=0
+
+    make check > build-phase2-tests.out
+
+    cat build-phase2-tests.out
+
+    if fgrep "============ ALL TESTS SUCCESSFUL" build-phase2-tests.out > /dev/null; then
+      TESTS_SUCCESS=1
+    fi
+
+    rm -f build-phase2-tests.out
+
+    if [ "$TESTS_SUCCESS" == "1" ] ; then
+      echo "************ TESTS SUCCESSFUL ($VARIANT variant)"
+    else
+      echo "************ TESTS FAILED ($VARIANT variant)"
+      cleanup
+      exit 1
+    fi
+
+  fi
+
+  make install
+  (cd "$SOURCE_DIR/$PACKAGE_VERSION" && bin/gsc syntax-case)
   cd "$herefromroot"
 }
 
diff --git a/prebuilt/windows/build b/prebuilt/windows/build
--- a/prebuilt/windows/build
+++ b/prebuilt/windows/build
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (c) 1994-2007 by Marc Feeley, All Rights Reserved.
+# Copyright (c) 1994-2008 by Marc Feeley, All Rights Reserved.
 
 herefromroot="prebuilt/windows"
 rootfromhere="../.."
@@ -20,8 +20,12 @@ for VARIANT in mingw visualc; do
   cd "$rootfromhere"
 
   case "$VARIANT" in
-      mingw) CONFIG_CC="gcc";;
-    visualc) CONFIG_CC="cl";;
+      mingw) CONFIG_CC="gcc"
+             RUN_TESTS=1
+             ;;
+    visualc) CONFIG_CC="cl.exe"
+             RUN_TESTS=0
+             ;;
   esac
 
   cmd /c "C:\PROGRA~1\MICROS~2\VC\VCVARS~1.BAT && C:\PROGRA~1\MICROS~4\SETENV.CMD /RETAIL && sh -c \"CC=\\\"$CONFIG_CC\\\" ./configure --prefix=\\\"$DOS_INSTALL_PREFIX\\\" --enable-single-host # --enable-gcc-opts\""
@@ -30,21 +34,29 @@ for VARIANT in mingw visualc; do
 
   chmod +x build-phase2
 
-  cmd /c "C:\PROGRA~1\MICROS~2\VC\VCVARS~1.BAT && C:\PROGRA~1\MICROS~4\SETENV.CMD /RETAIL && sh -c \"./build-phase2 \\\"$VARIANT\\\"\"" > build-phase2.out
+  cmd /c "C:\PROGRA~1\MICROS~2\VC\VCVARS~1.BAT && C:\PROGRA~1\MICROS~4\SETENV.CMD /RETAIL && sh -c \"./build-phase2 \\\"$VARIANT\\\" \\\"$RUN_TESTS\\\"\"" > build-phase2.out
 
   cat build-phase2.out
 
-  if fgrep "============ ALL TESTS SUCCESSFUL" build-phase2.out > /dev/null; then
-    rm -f build-phase2.out
-    echo "============ $VARIANT BUILD SUCCESSFUL"
+  SUCCESS=0
+
+  if fgrep "************ TESTS SUCCESSFUL" build-phase2.out > /dev/null; then
+    SUCCESS=1
   else
-    rm -f build-phase2.out
-    echo "============ $VARIANT BUILD FAILED"
-    exit 1
+    if fgrep "************ TESTS SKIPPED" build-phase2.out > /dev/null; then
+      SUCCESS=1
+    fi
   fi
 
   rm -f build-phase2.out
 
+  if [ "$SUCCESS" == "1" ] ; then
+    echo "************ BUILD SUCCESSFUL ($VARIANT variant)"
+  else
+    echo "************ BUILD FAILED ($VARIANT variant)"
+    exit 1
+  fi
+
 done
 
-echo "============ BUILD SUCCESSFUL"
+echo "************ windows BUILD SUCCESSFUL"
diff --git a/prebuilt/windows/build-phase2.in b/prebuilt/windows/build-phase2.in
--- a/prebuilt/windows/build-phase2.in
+++ b/prebuilt/windows/build-phase2.in
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (c) 1994-2007 by Marc Feeley, All Rights Reserved.
+# Copyright (c) 1994-2008 by Marc Feeley, All Rights Reserved.
 
 herefromroot="prebuilt/windows"
 rootfromhere="../.."
@@ -16,6 +16,7 @@ PACKAGE_SUBDIR="@PACKAGE_SUBDIR@"
 MAKENSIS="/c/Program Files/NSIS/makensis.exe"
 
 VARIANT="$1"
+RUN_TESTS="$2"
 
 SOURCE_DIR="$INSTALL_PREFIX"
 DOS_SOURCE_DIR="$DOS_INSTALL_PREFIX"
@@ -40,14 +41,35 @@ install_gambc()
   cd "$rootfromhere"
   make mostlyclean
   make
-  if ( make check | fgrep -e "============ ALL TESTS SUCCESSFUL" ) ; then
-    make install
-    (cd "$SOURCE_DIR/$PACKAGE_VERSION" && bin/gsc syntax-case)
+
+  if [ "$RUN_TESTS" == "0" ] ; then
+    echo "************ TESTS SKIPPED ($VARIANT variant)"
   else
-    echo "============ TESTS FAILED"
-    cleanup
-    exit 1
+
+    TESTS_SUCCESS=0
+
+    make check > build-phase2-tests.out
+
+    cat build-phase2-tests.out
+
+    if fgrep "============ ALL TESTS SUCCESSFUL" build-phase2-tests.out > /dev/null; then
+      TESTS_SUCCESS=1
+    fi
+
+    rm -f build-phase2-tests.out
+
+    if [ "$TESTS_SUCCESS" == "1" ] ; then
+      echo "************ TESTS SUCCESSFUL ($VARIANT variant)"
+    else
+      echo "************ TESTS FAILED ($VARIANT variant)"
+      cleanup
+      exit 1
+    fi
+
   fi
+
+  make install
+  (cd "$SOURCE_DIR/$PACKAGE_VERSION" && bin/gsc syntax-case)
   cd "$herefromroot"
 }
 
